/**
 * @file Defines custom Express middleware functions.
 */

const Boom = require('@hapi/boom');

/**
 * A higher-order function that wraps an async callback to properly trigger the
 * Express error-handling middleware on errors.
 *
 * @param {Function} fn an async callback.
 * @returns {Function} an Express callback that resolves the wrapped async fn.
 */
const asyncWrapper = fn => (req, res, next) => {
  return Promise.resolve(fn(req, res, next)).catch(next);
};

/**
 * A catch-all error handler that sends a formatted JSON response.
 * Uses Boom to set the status code and provide consistent formatting.
 *
 * If using multiple error handlers, this should be the last one.
 *
 * @param {Object} err a javascript Error object.
 * @param {Object} req the Express request object.
 * @param {Object} res the Express response object.
 * @param {Function} next the Express next callback.
 */
const errorHandler = (err, req, res, next) => {
  let error = err;

  // Log the actual error for debugging
  console.error('Error details:', err);
  console.error('Error stack:', err.stack);

  // handle errors from the Plaid api (SDK v39+ uses response.data structure)
  if (error.response && error.response.data) {
    const { error_type, error_code, error_message, display_message } = error.response.data;
    const statusCode = error.response.status || 500;
    const message = display_message || error_message || 'Plaid API error';
    const baseError = new Error(message);
    error = Boom.boomify(baseError, {
      statusCode,
      data: { error_type, error_code }
    });
  } else if (error.name === 'PlaidError') {
    // Fallback for older SDK versions
    const baseError = new Error(error.error_message);
    error = Boom.boomify(baseError, { statusCode: error.status_code });
  }

  // handle standard javascript errors.
  if (!error.isBoom) {
    // Errors raised by middleware such as body-parser carry their own HTTP
    // status: a malformed JSON body is the caller's fault, not ours.
    //
    // Only 4xx is honored. A 5xx is still our failure, and Boom masks the
    // response message on exactly 500 and no higher, so passing 501+ through
    // would leak internal error text.
    //
    // The isAxiosError check is narrower than it looks: it only catches
    // upstream responses with an empty body, because anything with a body
    // is already claimed by the branch above, which re-emits the upstream
    // status. Plaid errors want exactly that, so this cannot simply be
    // hoisted — and isAxiosError cannot separate Plaid from Dwolla, since
    // the Plaid SDK is itself axios. An upstream Dwolla failure therefore
    // still reaches the caller with the vendor's own status.
    const status = error.status || error.statusCode;
    const isClientError =
      !error.isAxiosError &&
      Number.isInteger(status) &&
      status >= 400 &&
      status < 500;
    error = isClientError
      ? Boom.boomify(error, { statusCode: status })
      : Boom.boomify(error);
  }

  // these are generated by Boom, so they're guaranteed to exist.
  const { statusCode, payload } = error.output;

  // Include custom data (error_type, error_code) from Boom if present
  const response = error.data
    ? { ...payload, data: error.data }
    : payload;

  res.status(statusCode).json(response);
};

module.exports = { asyncWrapper, errorHandler };
