/**
 * @file Defines custom Express middleware functions.
 */

const Boom = require('@hapi/boom');

/**
 * A higher-order function that wraps an async callback to properly trigger the
 * Express error-handling middleware on errors.
 *
 * @param {Function} fn an async callback.
 * @returns {Function} an Express callback that resolves the wrapped async fn.
 */
const asyncWrapper = fn => (req, res, next) => {
  return Promise.resolve(fn(req, res, next)).catch(next);
};

/**
 * A catch-all error handler that sends a formatted JSON response.
 * Uses Boom to set the status code and provide consistent formatting.
 *
 * If using multiple error handlers, this should be the last one.
 *
 * @param {Object} err a javascript Error object.
 * @param {Object} req the Express request object.
 * @param {Object} res the Express response object.
 * @param {Function} next the Express next callback.
 */
const errorHandler = (err, req, res, next) => {
  let error = err;

  // Log the actual error for debugging
  console.error('Error details:', err);
  console.error('Error stack:', err.stack);

  // handle errors from the Plaid api (SDK v39+ uses response.data structure)
  if (error.response && error.response.data) {
    const { error_type, error_code, error_message, display_message } = error.response.data;
    error = new Boom(display_message || error_message || 'Plaid API error', {
      statusCode: error.response.status || 500,
      data: { error_type, error_code }
    });
  } else if (error.name === 'PlaidError') {
    // Fallback for older SDK versions
    error = new Boom(error.error_message, { statusCode: error.status_code });
  }

  // handle standard javascript errors.
  if (!error.isBoom) error = Boom.boomify(error);

  // these are generated by Boom, so they're guaranteed to exist.
  const { statusCode, payload } = error.output;

  // Log the payload being sent to client for debugging
  console.error('Sending error payload to client:', JSON.stringify(payload));

  res.status(statusCode).json(payload);
};

module.exports = { asyncWrapper, errorHandler };
